name: Trivy Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Trivy scan
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        security-checks: 'vuln,secret'
        exit-code: '1'
        ignore-unfixed: true
        format: 'table'
        output: '.github/workflows/trivy-results.txt'
        
    - name: Check for secrets
      run: |
        if grep -q 'Found' trivy-results.txt; then
          echo "Secrets found in the repository!"
          exit 1
        else
          echo "No secrets found."
        fi
